<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
	  <WarningsAsErrors>true</WarningsAsErrors>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
    <Content Remove="bundleconfig.json" />
  </ItemGroup>
 
 
  <ItemGroup>
    <Folder Include="Domain\Entities\" />
    <Folder Include="Domain\Enums\" />
    <Folder Include="Domain\Repositories\Abstract\" />
    <Folder Include="Domain\Repositories\EntityFraemwork\" />
    <Folder Include="Models\ViewComponents\" />
    <Folder Include="wwwroot\scss\" />
    <Folder Include="wwwroot\css\" />
    <Folder Include="wwwroot\img\" />
  </ItemGroup>

  <ItemGroup>
    <None Include="bundleconfig.json" />
    <None Include="Views\Shared\_Layout.cshtml" />
  </ItemGroup>

  <ItemGroup>
    <Content Update="wwwroot\css\main.css">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Content>
    <Content Update="wwwroot\js\breakpoints.min.js">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Content>
    <Content Update="wwwroot\js\browser.min.js">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Content>
    <Content Update="wwwroot\js\jquery.dropotron.min.js">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Content>
    <Content Update="wwwroot\js\jquery.min.js">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Content>
    <Content Update="wwwroot\js\main.js">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Content>
    <Content Update="wwwroot\js\util.js">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Content>
  </ItemGroup>

</Project>
