<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
	  <WarningsAsErrors>true</WarningsAsErrors>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
    <Content Remove="bundleconfig.json" />
  </ItemGroup>
 
 
  <ItemGroup>
    <Folder Include="Domain\Entities\" />
    <Folder Include="Domain\Enums\" />
    <Folder Include="Domain\Repositories\Abstract\" />
    <Folder Include="Domain\Repositories\EntityFraemwork\" />
    <Folder Include="Migrations\" />
    <Folder Include="Models\ViewComponents\" />
    <Folder Include="wwwroot\scss\" />
    <Folder Include="wwwroot\css\" />
    <Folder Include="wwwroot\img\" />
  </ItemGroup>

  <ItemGroup>
    <None Include="bundleconfig.json" />
    <None Include="Views\Shared\_Layout.cshtml" />
  </ItemGroup>

  <ItemGroup>
    <Content Update="wwwroot\css\main.css">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Content>
    <Content Update="wwwroot\js\breakpoints.min.js">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Content>
    <Content Update="wwwroot\js\browser.min.js">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Content>
    <Content Update="wwwroot\js\jquery.dropotron.min.js">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Content>
    <Content Update="wwwroot\js\jquery.min.js">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Content>
    <Content Update="wwwroot\js\main.js">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Content>
    <Content Update="wwwroot\js\util.js">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Content>
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.Identity.EntityFrameworkCore" Version="10.0.12" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Design" Version="10.0.12">
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
      <PrivateAssets>all</PrivateAssets>
    </PackageReference>
    <PackageReference Include="Npgsql.EntityFrameworkCore.PostgreSQL" Version="10.0.3" />
    <PackageReference Include="Swashbuckle.AspNetCore" Version="10.2.3" />
  </ItemGroup>
	<Target Name="CopyTinyMCE" BeforeTargets="Build">
    <ItemGroup>
      <TinyMCEFiles Include="$(NugetPackageRoot)tinymce\**\content\**\*.*" />
    </ItemGroup>
    <Copy SourceFiles="@(TinyMCEFiles)" 
          DestinationFolder="$(MSBuildProjectDirectory)\wwwroot\lib\tinymce\%(RecursiveDir)" 
          SkipUnchangedFiles="true" />
  </Target>
</Project>
